
		$('#owl-examples').owlCarousel({
			items:1,
			autoPlay:true,
			navigation:true,
			navigationText:["",""],
			itemsDesktop:[3000,1],
			itemsDesktopSmall:[1199,1],
			itemsTablet:[979,1],
			itemsTabletSmall:[768,1],
			itemsMobile:[479,1]
		});
		$('#owl-examples1').owlCarousel({
			items:1,
			autoPlay:true,
			navigation:true,
			navigationText:["",""],
			itemsDesktop:[3000,1],
			itemsDesktopSmall:[1199,1],
			itemsTablet:[979,1],
			itemsTabletSmall:[768,1],
			itemsMobile:[479,1]
		});
		$('#owl-examples2').owlCarousel({
			items:1,
			autoPlay:true,
			navigation:true,
			navigationText:["",""],
			itemsDesktop:[3000,1],
			itemsDesktopSmall:[1199,1],
			itemsTablet:[979,1],
			itemsTabletSmall:[768,1],
			itemsMobile:[479,1]
		});
		$('#owl-examples3').owlCarousel({
			items:3,
			autoPlay:true,
			pagination:true,
			navigation:true,
			navigationText:["",""],
			itemsDesktop:[3000,3],
			itemsDesktopSmall:[1199,3],
			itemsTablet:[850,2],
			itemsTabletSmall:[768,1],
			itemsMobile:[479,1]
		});
		$('#owl-examples4').owlCarousel({
			items:5,
			autoPlay:true,
			pagination:false,
			navigation:true,
			navigationText:["",""],
			itemsDesktop:[3000,5],
			itemsDesktopSmall:[1199,4],
			itemsTablet:[979,3],
			itemsTabletSmall:[768,2],
			itemsMobile:[479,1]
		});
